### ISSUE TITLE
Clone Not Working

### ISSUE THREAD

**Issue by AdamG100** [Alexr03/TCAdminGitClone#1]
HI Alex,

I have tried to clone a repo with the git clone it either just flashes with the loading spinner or sometimes says clone successful but there is no files in the file manager

Tried this URL: https://github.com/sannrp/FiveM-FSN-Framework

Also tried other random public repo's same result

**Comment by Alexr03** [comment]
Hi,
I just tried the URL on my one and it downloaded the .zip as FiveM-FSN-Framework.zip
Can you try to uncheck the extract option and see if it works like that? 

Also, what operating system is your master, compared to the remote you are doing git clone against?

**Comment by AdamG100** [comment]
So i uninstalled it and reinstalled the module tried downloading the zip only it downloaded.

Deleted the zip to try again and it doesnt download again. 

I cant get the download & extract option to work.

**Comment by Alexr03** [comment]
Hi, sorry for wait, been away for few days.

What operating system is your master and the remote that you are doing git clone on?

**Comment by AdamG100** [comment]
Hi Alex,

We use Windows for all our game servers

**Comment by Alexr03** [comment]
Is it possible your game file system permissions or your monitor configuration is not allowing .zip to be on a service?

**Comment by Alexr03** [comment]
Try 1.0.1 please.
